#ifndef GSPICE_GMC_DIODE_HPP
#ifndef GSPICE_GMC_DIODE_HPP

#include "gdi.hpp"
#include <cmath>
#include <vector>
#include <string>
#include <unordered_map>
#include <memory>

namespace gspice {

/**
 * GMC Compiled Native C++ Compact Model for 'diode'
 * Automatically generated by GMC (GSPICE Model Compiler).
 */
class GmcDiodeInstance : public GdiInstanceBase {
public:
    double Is_ = 1e-14;
    double N_ = 1.0;
    double Rs_ = 0.0;
    double BV_ = 1e+20;
    double IBV_ = 1e-10;
    double XTI_ = 3.0;
    double EG_ = 1.12;
    double Tnom_ = 27.0;
    double Cjo_ = 0.0;
    double Vj_ = 1.0;
    double M_ = 0.5;
    double ,_ = 0.0;
    double TT_ = 0.0;
    double area_ = 1.0;

    bool evaluate(
        const double* voltages,
        const GdiEvaluationRequest& request,
        GdiEvaluationResult& result) override {
        result.clear();

        // Node Voltage Unpacking
        double V_A = voltages[0];
        double V_C = voltages[1];

        // Evaluate Terminal Branch Probe Voltages
        double Vd = V_anode - V_cathode;

        // Model Equations (Analytic / Transcendentals)
        double Vt = 0.02585;
        double exp_arg = std::clamp(Vd / (N_ * Vt), -40.0, 40.0);
        double exp_val = std::exp(exp_arg);
        double Id = Is_ * (exp_val - 1.0);
        double gd = (Is_ / (N_ * Vt)) * exp_val;

        // Static Residual (F)
        if (request.static_residual) {
            result.static_residual.push_back({0, Id});   // Anode
            result.static_residual.push_back({1, -Id});  // Cathode
        }

        // Analytical Jacobian (dF/dx)
        if (request.static_jacobian) {
            result.static_jacobian.push_back({0, 0, gd});
            result.static_jacobian.push_back({0, 1, -gd});
            result.static_jacobian.push_back({1, 0, -gd});
            result.static_jacobian.push_back({1, 1, gd});
        }

        return true;
    }

    std::size_t numTerminals() const override { return 2; }
    std::size_t numInternalNodes() const override { return 0; }
    std::size_t numStates() const override { return 0; }
};

class GmcDiodeModule : public GdiModuleBase {
public:
    std::string modelName() const override { return "diode"; }

    std::vector<GdiParameter> listParameters() const override {
        return {
            {"Is", 1e-14, "", "", true},
            {"N", 1.0, "", "", true},
            {"Rs", 0.0, "", "", true},
            {"BV", 1e+20, "", "", true},
            {"IBV", 1e-10, "", "", true},
            {"XTI", 3.0, "", "", true},
            {"EG", 1.12, "", "", true},
            {"Tnom", 27.0, "", "", true},
            {"Cjo", 0.0, "", "", true},
            {"Vj", 1.0, "", "", true},
            {"M", 0.5, "", "", true},
            {",", 0.0, "", "", true},
            {"TT", 0.0, "", "", true},
            {"area", 1.0, "", "", true},
        };
    }

    std::unique_ptr<GdiInstanceBase> createInstance(
        const std::unordered_map<std::string, double>& modelParams,
        const std::unordered_map<std::string, double>& instanceParams) override {
        auto instance = std::make_unique<GmcDiodeInstance>();
        auto it_Is = modelParams.find("Is"); if (it_Is != modelParams.end()) instance->Is_ = it_Is->second;
        auto it_N = modelParams.find("N"); if (it_N != modelParams.end()) instance->N_ = it_N->second;
        auto it_Rs = modelParams.find("Rs"); if (it_Rs != modelParams.end()) instance->Rs_ = it_Rs->second;
        auto it_BV = modelParams.find("BV"); if (it_BV != modelParams.end()) instance->BV_ = it_BV->second;
        auto it_IBV = modelParams.find("IBV"); if (it_IBV != modelParams.end()) instance->IBV_ = it_IBV->second;
        auto it_XTI = modelParams.find("XTI"); if (it_XTI != modelParams.end()) instance->XTI_ = it_XTI->second;
        auto it_EG = modelParams.find("EG"); if (it_EG != modelParams.end()) instance->EG_ = it_EG->second;
        auto it_Tnom = modelParams.find("Tnom"); if (it_Tnom != modelParams.end()) instance->Tnom_ = it_Tnom->second;
        auto it_Cjo = modelParams.find("Cjo"); if (it_Cjo != modelParams.end()) instance->Cjo_ = it_Cjo->second;
        auto it_Vj = modelParams.find("Vj"); if (it_Vj != modelParams.end()) instance->Vj_ = it_Vj->second;
        auto it_M = modelParams.find("M"); if (it_M != modelParams.end()) instance->M_ = it_M->second;
        auto it_, = modelParams.find(","); if (it_, != modelParams.end()) instance->,_ = it_,->second;
        auto it_TT = modelParams.find("TT"); if (it_TT != modelParams.end()) instance->TT_ = it_TT->second;
        auto it_area = modelParams.find("area"); if (it_area != modelParams.end()) instance->area_ = it_area->second;

        return instance;
    }
};

} // namespace gspice

#endif // GSPICE_GMC_DIODE_HPP
